#import '../../../graphql/description.gql'
#import '../../../graphql/id.gql'
#import '../../../graphql/price.gql'
#import '../../../graphql/title.gql'
#import '../../../../category/graphql/id.gql'
#import '../../../../../views/cart/components/add-to-cart-action-button/graphql/data.gql'

fragment productCardData on Product {
	...productTitleData
	...productDescriptionData
	...productPriceData
	...productIdData
	images
	category {
		...categoryIdData
		...categoryNameData
	}
	...addToCartActionButtonData
}
